apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
  annotations:
    sidecar.istio.io/inject: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
      annotations:
        traffic.sidecar.istio.io/includeOutboundIPRanges: "*"
        traffic.sidecar.istio.io/protocolPorts: "http:3000"
    spec:
      containers:
      - name: service1
        image: darron/anthos-service1:06f4d094e1034c9caa9d895ea4345c0451588e00
        ports:
        - containerPort: 3000
          name: http
        resources:
          requests:
            cpu: "10m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-curl
  annotations:
    sidecar.istio.io/inject: "true"
spec:
  replicas: 5
  selector:
    matchLabels:
      app: service1-curl
  template:
    metadata:
      labels:
        app: service1-curl
      annotations:
        traffic.sidecar.istio.io/includeOutboundIPRanges: "*"
    spec:
      containers:
      - name: service1-curl
        image: darron/anthos-service1:curl
        resources:
          requests:
            cpu: "10m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  selector:
    app: service1
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  type: ClusterIP