apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
  annotations:
    sidecar.istio.io/inject: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
      annotations:
        traffic.sidecar.istio.io/includeOutboundIPRanges: "*"
        traffic.sidecar.istio.io/protocolPorts: "http:3000"
    spec:
      containers:
      - name: service1
        image: darron/anthos-service1:efbb71a784d298610055064cd034b91743072f36
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  selector:
    app: service1
  ports:
  - name: http
    port: 80
    targetPort: 3000
  type: ClusterIP